[package]
name = "rustformers"
description = "a transformers like interface for interacting with local LLMs"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ljt019/rustformers/"

[dependencies]
anyhow = "1.0.98"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
hf-hub = "0.4.2"
minijinja = "2.9.0"
tokenizers = "0.21.1"
