[package]
name = "rustformers"
description = "Rust transformers"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ljt019/rustformers/"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.9.0" }
