[package]
name = "transformers"
description = "A transformers like interface for interacting with local LLMs"
version = "0.0.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ljt019/transformers/"

[dependencies]
anyhow = "1.0.98"
candle-core = { git = "https://github.com/ljt019/candle", version = "0.9.1" }
candle-nn = { git = "https://github.com/ljt019/candle", version = "0.9.1" }
candle-transformers = { git = "https://github.com/ljt019/candle", version = "0.9.1" }
hf-hub = "0.4.2"
minijinja = "2.9.0"
tokenizers = "0.21.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
  