[package]
name = "rustformers"
description = "A transformers like interface for interacting with local LLMs"
version = "0.0.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ljt019/rustformers/"

[dependencies]
anyhow = "1.0.98"
candle-core = { path = ".external_crate_test/candle/candle-core", version = "0.9.0" }
candle-nn = { path = ".external_crate_test/candle/candle-nn", version = "0.9.0" }
candle-transformers = { path = ".external_crate_test/candle/candle-transformers", version = "0.9.0" }
hf-hub = "0.4.2"
minijinja = "2.9.0"
tokenizers = "0.21.1"
